#################################################################################
# COMMANDS                                                                      #
#################################################################################

venv:
	python3 -m venv .venv

requirements:
	.venv/bin/pip install --upgrade pip
	.venv/bin/pip install -r requirements.txt

git:
	git init
	git add --all
	git commit -m "initial commit"
